Repository DevKosov/realtime_SVGClock, pull requests merged in 2020-10, with the labels that each got.

#1 Added Sound Toggle Button
  css.css
  css.css.map
  css.scss
  font/OFL.txt
  index.html
  script.js
Labels: hacktoberfest

#2 Added button
  css.css
  css.css.map
  css.scss
  font/OFL.txt
  index.html
  script.js
Labels: hacktoberfest-accepted

#3 Added feature to play own mp3 file from URL
  css.css
  index.html
  script.js
Labels: hacktoberfest-accepted

#4 added functionality to use own bg image from url
  css.css
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#5 Improved code + removed css errors
  css.css
  img/favicon.ico
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted
